### PR TITLE
fixed a bunch of dead links

### PR DESCRIPTION
**Pull request by jarrodwb**
My editor, Atom, is also making a bunch of changes related to
whitespace. :-(

### CODE REVIEW

**Comment by SethTisue** [comment]
Thanks, this is terrific, the work is really appreciated.

I suggest we merge even with the whitespace changes, but for next time it would be better if you disabled the feature — it looks there's hints on that at https://github.com/atom/whitespace/issues/10

**Comment by heathermiller** [comment]
(I'm guilty of also being a white space squasher, and I *love* it in pull requests. But I realize I might just be a crazy person)

**Comment by heathermiller** [comment]
In any case, **THANK YOU @jarrodwb**!!

**Comment by jarrodwb** [comment]
Sure @SethTisue. I will take more care about it for the next one.

I do prefer files with spaces swashed but I do not feel strongly about it if I did not write the original file.

**Pull request merged**
