### PR TITLE
Added scala annotation for code segments to SIP

### PR DESCRIPTION
**Pull request by soronpo**

### CODE REVIEW

**Comment by soronpo** [comment]
@jvican Please merge so I can see if this resolved the problem.

**Comment by SethTisue** [comment]
> Please merge so I can see if this resolved the problem

are you unable to build the site locally? (or is this an issue where the local rendering and the rendering on the site differ somehow...?)

**Comment by jvican** [comment]
FTR @soronpo, you can build the site yourself. Check the README :wink:.
  
Merging since everything is green. And hell yeah, I love green.

**Comment by soronpo** [comment]
You guys are right. Unfortunately, I'm currently having local build issues. Now that I rechecked the file on the site and see it's still bad (or even worse), I conclude I must fix my build issues and check things locally.

**Comment by soronpo** [comment]
I recommend that you add this as a requirement for a the GitHub SIP review process, by requesting each proposal will be viewed locally by the PR submitter and he/she would confirm that everything is OK. I assumed that if it looks OK as MD, it will look OK on the site. This is evidently wrong :disappointed:

**Comment by jvican** [comment]
I would consider adding that to the rules and the process, thanks for the suggestion @soronpo.

**Pull request merged**
