### PR TITLE
Added Scala with Maven tutorial

### PR DESCRIPTION
**Pull request by Raekye**
- Basic Maven information
- Usage with [scala-maven-plugin](https://github.com/davidB/scala-maven-plugin)

### CODE REVIEW

**Comment by Raekye** [comment]
Hi @retronym,

Sorry for my delay getting back. I just ran through it again and made couple minor updates. As for the "state of the art", I didn't find any newer/better scala plugins, but I usually use Gradle now because its Scala integration is much more streamlined (their docs/tutorial cover this well).

I've also linked to the sample project

**Comment by retronym** [comment]
Thanks! I've just sent a [note out to scala-internals](https://mail.google.com/mail/u/0/?zx=evixquqxsn7l#sent) to see if I can find another reviewer with Maven smarts. I aim to merge this by the end of the week.

**Comment by retronym** [comment]
We got this suggestion on the mailing list:

> m2e and https://github.com/sonatype/m2eclipse-scala

> should be mentioned as alternatives to the maven-eclipse-plugin.   There are advantages and disadvantages to each; I prefer m2e.

**Comment by Raekye** [comment]
I'll take a look and add instructions soon. Thanks!

**Comment by Raekye** [comment]
@retronym I've added instructions on installing m2eclipse-scala and importing/starting a new project

**Comment by retronym** [comment]
Thank you. I'm merging now, perhaps you can double check how it looks on the site (might take up to 30m to propagate).

**Comment by Raekye** [comment]
I checked it at http://docs.scala-lang.org/tutorials/scala-with-maven.html and it looks good, and I'll try to keep it updated. By the way, is there supposed to be an index of tutorials? On http://docs.scala-lang.org/tutorials/ there's the tour of the language on the right, FAQs and language guides on the left

**Comment by retronym** [comment]
Looks like you'll have to add your new tutorial to the index by hand. /cc @heathermiller for guidance on the layout. We might want to add placeholders for SBT and Gradle (even if they just link to third party docs) so as to have a "Building your Code" section in the index.

**Comment by heathermiller** [comment]
There are some rendering errors on the layout.

**Comment by heathermiller** [comment]
Got it, looks like there was just one :) Thanks for the contribution!

**Pull request merged**
