### PR TITLE
Update control-structures.md

### PR DESCRIPTION
**Pull request by propensive**
Reflect current thinking on non-usage of curly braces in case clauses.

### CODE REVIEW

**Comment by dickwall** [comment]
Well, I agree, LGTM, however will give this a day or so to see if there are any dissenting opinions (pardon me, is this Contradiction? Oh, I was looking for Arguments, they're down the hall on the left...)

**Comment by SethTisue** [comment]
Pretty sure there was a mailing list thread on this not long ago and the mob was unanimously in favor of this change. I have never seen a codebase that used the old rule.

**Comment by dickwall** [comment]
Right on - merging it in then.

**Comment by SethTisue** [comment]
for the record, here's the thread: https://groups.google.com/d/msg/scala-debate/ZH2XiimsC0k/Jghw8pKUCl4J

**Pull request merged**
