### PR TITLE
Fatal warnings

### PR DESCRIPTION
**Pull request by jarrodwb**
Here is the rest of the improvements for the `tut` and the fixes to the tour to make `tut` pass.

### CODE REVIEW

**Comment by jarrodwb** [comment]
fixes #606

**Comment by heathermiller** [comment]
LGTM, thanks @jarrodwb!

**Comment by SethTisue** [comment]
sweet!

**Comment by mpociecha** [comment]
Wouldn't it be better to just squash such commits before merging PRs? It doesn't make sense to merge merge commits etc.

**Comment by jarrodwb** [comment]
Yup. I agree. I was tired and wanted to get the PR summited before I went to bed.

Not my best work for sure. The commits are a bit embarrassing.

**Pull request merged**
