### PR TITLE
minor tweaks to code of conduct page

### PR DESCRIPTION
**Pull request by SethTisue**
review by @dickwall plz

note that all of the actual substance is in ac8d836be0296c2e2bc45c69eb5b787eb299a344, the rest is just typos and formatting

### CODE REVIEW

**Comment by SethTisue** [comment]
review also by @jsuereth? note that the descriptions of the mailing lists here have different wording than the ones on the other page; I think you might have written these ones

**Comment by dickwall** [comment]
Otherwise, LGTM

**Comment by SethTisue** [comment]
commit added with improved grammar and wording.

**Comment by SethTisue** [comment]
taking a second look at this, Josh's descriptions of the lists here are really better in many respects than the other set over on the Community page, so I'm now working on merging them.

**Comment by SethTisue** [comment]
merging this. interested parties will want to review https://github.com/scala/scala-lang/pull/329 as well

**Pull request merged**
