### PR TITLE
`Queue` supports constant time `prepend`

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
Evidence: https://github.com/scala/scala/blob/05016d9035ab9b1c866bd9f12fdd0491f1ea0cbb/src/library/scala/collection/immutable/Queue.scala#L100

**Comment by SethTisue** [comment]
shouldn't at least one of `prepend` and `append` be `eC`, not `C`, because of the occasional need to pivot?

**Comment by SethTisue** [comment]
also, can you change the commit message to refer to `Queue` instead of `Stack`?

**Comment by Atry** [comment]
Both `prepend` and `append` for `Queue` are `C`, not `eC`. See https://github.com/scala/scala/blob/05016d9035ab9b1c866bd9f12fdd0491f1ea0cbb/src/library/scala/collection/immutable/Queue.scala#L100 and https://github.com/scala/scala/blob/05016d9035ab9b1c866bd9f12fdd0491f1ea0cbb/src/library/scala/collection/immutable/Queue.scala#L114

**Comment by SethTisue** [comment]
doh, you're right, it only pivots when you dequeue, an operation that isn't represented in the chart. sorry

**Pull request merged**
