### PR TITLE
WIP: merging look and feel of scala-lang with doc site

### PR DESCRIPTION
**Pull request by heathermiller**
Todos before this can be merged
- [x] Restore lost SIPs/SLIP pages
- [x] Fix broken translation links on landing page
- [x] Restore footer
- [x] Restore Java to Scala guide
- [x] Restore style guide
- [x] Language dropdown box instead of unordered list
- [x] Fix syntax highlighting
- [x] Remove "what is Scala" on landing page 
- [x] Fix glossary styling
- [x] Rearrange landing page masthead (some important things are swallowed, like list of previous API docs)
- [x] Need a nav bar for docs
- [x] Overview pages need subtitles
- [x] Rework overviews landing page
- [x] Doc template
- [x] Rework TOCs
  - [x] Based on collections instead
  - [x] Expand TOC elements for current page
  - [x] Language switcher
- [x] Multipage overview templates w/ language switch
- [x] Singlepage overview templates w/ language switch
- [x] Tour w/ language switch
- [x] Tutorials w/ language switch
- [x] Fix cheatsheet styling
- [x] Tutorials landing page
- [x] SIP layouts
- [x] SIP index page
- [x] Make it possible to use tut AND rouge syntax highlighting
- [x] Sort out getting started guides
- [x] All versions of API docs page
- [x] Improve formatting of index page of style guide

Nice to haves, but not required for merge:
- Make cheatsheets table more responsive (breaks on very small screens)
- New algolia search
- Fit search bar into doc navigation bar

...more forthcoming

### CODE REVIEW

**Comment by SethTisue** [comment]
holy moly

**Comment by heathermiller** [comment]
Seems some links are broken on the site I uploaded to my EPFL homepage. Fixing it for review would mean adding unnecessary liquid markup to nagivation bars, which I can do, but would rather not. 

That said, it might be easiest to just checkout and build locally for review, @SethTisue. 

I got build times down to only ~40 seconds, btw.

**Comment by heathermiller** [comment]
Anyway, I think the overhaul is done and ready to be merged.

@SethTisue, I'd suggest that if you're mostly happy with everything, we discuss here what should be changed, open up tickets for any must-dos, and merge this without adding anymore commits to this thing. It's already way too huge of a PR.

**Comment by heathermiller** [comment]
Seems like this attempt at uploading the site works:
http://lampwww.epfl.ch/~hmiller/new-docsite

**Comment by SethTisue** [comment]
@heathermiller this looks like an enormous improvement to me. consider me fine with you merging it. we can all help gradually sort out any needed tweaks or minor regressions afterwards.

> I got build times down to only ~40 seconds, btw.

niiiiice!

**Comment by heathermiller** [comment]
👍 Merci sir!

...Merge commencing...

**Pull request merged**
