### PR TITLE
Propose clarifying constructor invocation

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Comment by SethTisue** [comment]
I started a thread on this at https://groups.google.com/d/msg/scala-language/rtkamhSxv-Q/09Y_NnMbMocJ

**Comment by SethTisue** [comment]
Closing for lack of sufficient consensus, in my judgment.

**Comment by SethTisue** [comment]
Nonetheless, it's a little odd that the style guide doesn't touch on the issue at all. Right now the style guide tends to remain silent on such issues. I'd be fine with a revised text that mentioned this — and/or other such points — and says that preferred styles vary.

**Comment by sksamuel** [comment]
I think the 1 year it took to get any interest in this means I don't think there is any, and it could just be left unspecified :)

**Pull request closed without merging**
