### PR TITLE
modify japanese expression

### PR DESCRIPTION
**Pull request by KenjiOhtsuka**
reflect reviews into the code, which are given at
https://github.com/scala/scala.github.com/pull/418

Some reviews were not reflected.
* "イテレート" was not changed to "捜査", because I think "イテレート" is more frequently used than "捜査".
* "次と同じ" was not changed to "は次と同じ", because I think "same as" doesn't make sentence. "は次と同じ" is appropriate when English expression is "is the same as".

Please let me know your opinion.

@eed3si9n @kmizu @taku0 @takezoux2

### CODE REVIEW

**Comment by eed3si9n** [comment]
My suggestion was to use to "走査" not "捜査", reflecting the term that's used to translate *traverse* in http://docs.scala-lang.org/ja/overviews/collections/trait-traversable.html. I feel the English original should also be changed to *traverse* instead of *iterate*.

**Comment by KenjiOhtsuka** [comment]
@eed3si9n 
I changed "イテレート" to "走査".

**Comment by taku0** [comment]
How about those translations? I would adopt the second one if 「は次と同じ」 is not a option.
- `if (check) happy else ()` _と同等である_ <br> `if (check) happy`
- `if (check) happy` <br> (`if (check) happy else ()` _と同じ_)

I am not strongly against with 「次と同じ」. We cannot translate it perfectly after all.

**Comment by taku0** [comment]
ところで

`package pkg` _ファイルの先頭で_ <br> `package pkg { ... }`

だと「ファイルの先頭で」がどちらにかかるのか分かりにくいので

_ファイルの先頭で_ `package pkg` <br> `package pkg { ... }`

_ファイル先頭の_ `package pkg` <br> `package pkg { ... }`

か

 `package pkg` (_ファイルの先頭で_) <br> `package pkg { ... }`    

のほうがよいのではないでしょうか。

**Comment by KenjiOhtsuka** [comment]
@taku0 

> if (check) happy else () と同等である 
> if (check) happy
> if (check) happy 
> (if (check) happy else () と同じ)

second one looks good.

**Comment by SethTisue** [comment]
@eed3si9n lgty?

**Comment by eed3si9n** [comment]
LGTM

**Comment by SethTisue** [comment]
thanks all! appreciated

**Pull request merged**
