### PR TITLE
SIP for supporting named type arguments and partial type argument lists

### PR DESCRIPTION
**Pull request by ahmadsalim**
This follows directly from the discussion in [scala-debate](https://groups.google.com/forum/#!topic/scala-debate/tGMUQzSCsKc) and other relevant discussion mentioned in the SIP.

All comments are welcome.

### CODE REVIEW

**Comment by dickwall** [comment]
Please fix the formatting for the code examples. This will be reviewed again in the December SLIP meeting.

**Comment by SethTisue** [comment]
sorry for the delay @ahmadsalim, we inadvertently lost this in the shuffle

**Comment by SethTisue** [comment]
sorry, we ended up having to canceling the December meeting SIP/SLIP where this would have been discussed — we will reschedule for January.

**Comment by ahmadsalim** [comment]
Sure, I will look forward to hear your response.

**Comment by SethTisue** [comment]
we discussed this at the SLIP/SIP meeting today, video link https://www.youtube.com/watch?v=Kp4Ev-2xjWU. full notes from the meeting aren't up yet, but I would summarize as follows: all are sympathetic, but the proposal as its stands is not sufficiently detailed to qualify as a SIP yet. there is speculative work on named type parameters happening in a Dotty context, with the motivation going beyond just supporting partial type application; that's the likeliest path forward for something in this space, so we suggest engaging the Dotty team on it.

**Comment by SethTisue** [comment]
more detailed notes: http://www.scala-lang.org/blog/2016/01/11/minutes-from-jan-2016.html

**Comment by ahmadsalim** [comment]
@SethTisue Thank you and the committee for taking time to discuss my proposal, I can certainly see your points that there are issues there that needs to be fleshed out. I will try to contact the dotty team soon and see what further development there is needed.

**Comment by jvican** [comment]
Hi @ahmadsalim! Is there any news or progress on this?

**Comment by ahmadsalim** [comment]
@jvican Hi.

So as far as I understand my SIP draft was nowhere near complete to be converted to an official SIP. At the SLIP meeting, the responsible actors stated that they were currently developing something overlapping in the dotty team, and suggested I should contact them to coordinate.

I wrote an e-mail to the dotty developers mailing list around that time (January), but I unfortunately did not get any response back then (and thus moved on to doing other things more relevant to my work). I would however still assume that the Dotty team has something under development with regards to this aspect, and so I would try to contact them about the state of affairs if you are interested in this features.

In any case, thank you for the interest. I will close the PR now, which I long had forgotten to do.

**Comment by jvican** [comment]
Hi @ahmadsalim, I suggest you to contact @smarter, @felixmulder or @DarkDimius for more information on the dotty side. Hope that you reopen this soon. Thanks to you!

**Comment by felixmulder** [comment]
This was at one point implemented in Dotty, but it was removed because of performance issues with the implementation. @DarkDimius knows more.

Cheers,
Felix

**Comment by ahmadsalim** [comment]
@jvican @felixmulder Ah great, thanks for the update!

**Comment by Blaisorblade** [comment]
Fixed in Dotty 0.8.0-RC1:
```scala
scala> def f[A, B](x: A, y: B) = x
def f[A, B](x: A, y: B): A
scala> f[A = Int](_, "")
val res2: Int => Int = Lambda$1344/204568533@76f856a8
```

**Pull request closed without merging**
