### PR TITLE
added pending SIP-??? Backticks in String Interpolation

### PR DESCRIPTION
**Pull request by kevinwright**

### CODE REVIEW

**Comment by kevinwright** [comment]
Okay - I've rewitten the document to make the intent clearer here, and to remove the enhanced proposal which (I must admit) was somewhat aspirational.

**Comment by SethTisue** [comment]
@som-snytt has a PR on this at https://github.com/scala/scala/pull/4663

**Comment by som-snytt** [comment]
It turns out that without a number, you're nuthin'.

**Comment by jvican** [comment]
Hey @som-snytt, we'll be discussing this SIP in the September meeting, it's already on my notebook :wink:.

**Comment by som-snytt** [comment]
@jvican Oh wow, Scala Center is really shaking things up.

Wait, do you mean it's on the agenda for this September or last September?

**Comment by jvican** [comment]
This September, of course!

**Comment by jvican** [comment]
I have just realised that this SIP [was already discussed and rejected](https://github.com/scala/slip/issues/3). Therefore, it won't be considered for review again. Thanks for participating!

**Pull request closed without merging**
