### PR TITLE
Differ between PascalCase and camelCase

### PR DESCRIPTION
**Pull request by paulclarkin**
"camelCase" with a Capital First Letter is known as PascalCase (c2.com/cgi/wiki?PascalCase).

### CODE REVIEW

**Comment by SethTisue** [comment]
not convinced this is a good change. I don't recall ever hearing or seeing the term "PascalCase" before. Wikipedia only mentions it in passing and says its used "in Microsoft documentation". I see and hear "camel case" used to refer interchangeably to both `FooBar` and `fooBar` style naming. and Pascal itself is a historical relic these days so it doesn't seem like a great term to me.

**Comment by paulclarkin** [comment]
Maybe it's my .NET background but its a familiar term to me. It is used in Microsoft documentation because one of the Pascal designers worked on earlier .NET versions (http://blogs.msdn.com/b/brada/archive/2004/02/03/67024.aspx) and it removes the ambiguity between `CamelCase` and `camelCase`.

I prefer to remove the ambiguity, but that's up to you.

**Comment by heathermiller** [comment]
I second Seth. I've never seen this referred to as PascalCase before.

**Comment by dwijnand** [comment]
FWIW it's the term I also use to be less ambiguous than "camel case" and more terse than "upper-case camel case". But I guess it's not ubiquitous enough.

It's a shame there's no strong candidate substitute for "lower-case camel case".

If anything this pull request shows there's some difference in how camel case is referred to in the docs.

**Comment by SethTisue** [comment]
I took a new stab at at least regularizing the existing usage in #474. @paulclarkin, sorry we didn't take the change, but we appreciate your attention to this.

**Pull request closed without merging**
