### PR TITLE
Update concrete-immutable-collection-classes.md

### PR DESCRIPTION
**Pull request by AbnerZheng**
常熟->常数

### CODE REVIEW

**Comment by heathermiller** [comment]
Hi @AbnerZheng thanks for your contribution! In theory this LGTM, I admit my Chinese is a bit rusty :P I don't know of any Chinese-speakers off-hand that I could ask to review this.

Is there someone you could suggest that could have a look?

**Comment by SethTisue** [comment]
@apapi, interested in reviewing?

**Comment by som-snytt** [comment]
It's a clever pun on "constant time" and "the time is ripe". Unfortunately, my spouse, who hates all my puns, is visiting in China this week. But google says, 对我来说很好。

**Comment by SethTisue** [comment]
I asked for a reviewer on scala/contributors. If nobody turns up I guess we should just merge

**Comment by SethTisue** [comment]
@marky0720 interested in reviewing this?

**Comment by som-snytt** [comment]
LGTM

OK, my wife is back from China yesterday. She confirms the fix. She also got my pun; or possibly is just being nice about it.

**Comment by floating-cat** [comment]
I am a Chinese. This PR is just a typo fix. You can merge this commit without any worries.

**Comment by heathermiller** [comment]
Thanks all!

**Pull request merged**
