### PR TITLE
Adds Chinese translation (Subsumes #280)

### PR DESCRIPTION
**Pull request by eed3si9n**
Subsumes #280 by fixing file naming and localization mechanics.

The credit for the actual translation work goes to the following 21 individuals listed on https://code.csdn.net/DOC_Scala/chinese_scala_offical_document

- 陈骏	jacty0219	Jacty
- 陈幸	Meteor2520	meteor2520
- 董泉	dqsweet	dqsweet
- 何乃梧	yuyi20112011	yuyi20112011
- 黄越勇	aptweasel	brucehuang
- 赖正兴	laizx	laizx
- 李奕飞	fancylee	SarahCla
- 林君	a455642158	玲渱胾
- 刘国锋	iceongrass	iceongrass
- 吕浩志	lvhaozhi	smile_lhz
- 聂雪珲	blueforgetmenot	blueforgetmenot
- 潘栋华		pandonghua
- 潘义文	Caidaoqq	Paner
- 王金岩	i9901028	VV一笑
- 王雨施		m00nlight
- 熊杰	xiaoxiong345064855	jjxiong
- 杨志斌	qwewegfd	qwewegfd
- 张冰	usen521	Flicy
- 张明明	a775901421	zhangmingming
- 张欣	kevenking@gmail.com	kevenking
- 周逸灵	pastgift	

According to Google Translate the page says:

> From October 2013, CSDN CODE began organizing volunteers to translate official documents Scala. > Plan translated documents Scala main content overview section of the official website, includes the following sections:  ....
>
> After an open call screening, we finally organized a dozen volunteers to carry out this translation work. We invite to the well-known domestic Scala community Scala研学社 ("Scala research society") two teachers 连城 and 尹绪森 as a consultant and translation proofreading work. To express my heartfelt thanks to Scala Society Institute!
>
> Special thanks also to the hard work is paying in the translation work, the majority of the volunteer interpreters friends, they are:
> (Hereinafter sorted by last name spelling)

## screenshots

index_-_scala_documentation

collections_-_intro_-_scala_documentation

### CODE REVIEW

**Comment by heathermiller** [comment]
Thanks for figuring this all out Eugene! ...It's a huge piece of work and sad that it sat in limbo so long. Thanks for rescuing it! LGTM

**Comment by eed3si9n** [comment]
Maybe the translation work was done in a short period of time by the above members, but there are variance around basic terms like "collections" (容器类, 集合, 集实体类). The next step I think should be recruit someone (@fsi206914, could you help here?) who can write in Mandarin to:

- Notify the Scala研学社 ("Scala research society") that we merged this.
- Ask the society people and other volunteers to submit subsequent pull requests here to unify some of the terms.

/cc @pengisgood @XuefengWu @jasonqu

**Comment by eed3si9n** [comment]
@heathermiller Thanks for the quick merge :)

**Comment by fsi206914** [comment]
@eed3si9n Any contact method to reach them?

**Comment by eed3si9n** [comment]
@fsi206914 I don't even know if Scala研学社 is an active community or not, so I was hoping you could find out. It might be better to just send email out to [Scala中文社区][1] if that's active.

  [1]: https://groups.google.com/forum/#!forum/scalacn

**Pull request merged**
