### PR TITLE
Replaced disqus with discourse

### PR DESCRIPTION
**Pull request by travissarles**
I could only partly test this locally because of CORS being disabled. However, it looks like it embeds properly.

### CODE REVIEW

**Comment by SethTisue** [comment]
addresses #744

**Comment by heathermiller** [comment]
Woohoo! 👍  Ok, merging optimistically – we can revert or add follow-up commits if anything looks amiss.

**Comment by SethTisue** [comment]
@travissarles this is still on the front page:

screen shot 2017-06-06 at 3 04 19 pm

on e.g. the tour pages themselves, the Disqus stuff has disappeared, but I don't see any new Discourse stuff yet

**Comment by travissarles** [comment]
We're having CORS issues. I'm trying to figure it out. Let me know if you have any ideas.

```
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://docs.scala-lang.org" from accessing a cross-origin frame.
```

```
VM4658 comments?embed_url=http%3A%2F%2Fdocs.scala-lang.org%2Ftutorials%2Ftour%2F_posts%2F2017-02-13…:16 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://users.scala-lang.org') does not match the recipient window's origin ('http://docs.scala-lang.org').
```

**Pull request merged**
