### PR TITLE
SIP for adding co-monadic comprehensions

### PR DESCRIPTION
**Pull request by shimib**

### CODE REVIEW

**Comment by jvican** [comment]
Hello @shimib!
  
Thank you for submitting a SIP and helping us improving Scala. After the discussions The SIP Committee will review this proposal this month since the Community has already discussed this idea.
  
I think the proposal is great. I just have one suggestion: could you make it more obvious that this proposal enjoys of an existing implementation? Perhaps a few sentences in the introduction would be great.
  
I'm happy to merge this as soon as it's ready so that we can all see it in the official SIP website :wink:.

**Comment by shimib** [comment]
@jvican done :)

**Comment by shimib** [comment]
@jvican is there something more needed from me for merging this SIP?

**Comment by jvican** [comment]
No :smile:. Let's do it.

**Comment by shimib** [comment]
:)

**Comment by jvican** [comment]
Hello @shimib, I'm adding this to the upcoming SIP meeting happening this month! Thanks for your work :smile:.

**Comment by shimib** [comment]
Thanks @jvican , I really appreciate it :)

**Pull request merged**
