### PR TITLE
Improve punctuation in Polish translation

### PR DESCRIPTION
**Pull request by mpociecha**
Other than that there are a few changes related to wording etc.

### CODE REVIEW

**Comment by mpociecha** [comment]
@adamwy Could you take a look?

**Comment by jvican** [comment]
Can you please rebase on top of https://github.com/scala/scala.github.com/pull/685?

**Comment by mpociecha** [comment]
Okay, I'll do this in the evening.

**Comment by jvican** [comment]
Thanks @mpociecha, there's no rush :wink:.

**Comment by mpociecha** [comment]
@Krever Maybe could you take a look? :)

**Comment by charafau** [comment]
I also scanned the PR. Looks good but I also suck at punctuation. Thanks!

**Comment by jvican** [comment]
@Krever @charafau Thank you very much for your reviews guys :smile:.
  
Should we go ahead and merge @heathermiller?

**Comment by heathermiller** [comment]
🎉🎉 Woohoo!! 🎉🎉 Thank you everybody for your reviews! And of course, thank you @mpociecha for these improvements! 😄

**Pull request merged**
