### PR TITLE
Added singleton-object page in Korean

### PR DESCRIPTION
**Pull request by openmaya**
and View page was updated because it moved to Implicit-conversions.

### CODE REVIEW

**Comment by jvican** [comment]
Hey @openmaya, could you please rebase on top of latest master?
  
@SethTisue @heathermiller Shall we merge optimistically on this one? My level on Korean is not that great, yet -- but this PR looks like a good improvement!

**Comment by SethTisue** [comment]
I called for reviewers on scala/scala Gitter just now, let's see if that produces some review

**Comment by openmaya** [comment]
@jvican Okay I'll try it

**Comment by openmaya** [comment]
@jvican I did it :)

**Comment by openmaya** [comment]
@heathermiller could you check my branch?

**Comment by heathermiller** [comment]
LGTM, thanks @openmaya!

**Pull request merged**
