### PR TITLE
add Chinese translation document

### PR DESCRIPTION
**Pull request by imsingo**
The pull request contains the Chinese translation for "Guide and Overviews (Core)" part. 

The translation covers the doc in http://docs.scala-lang.org/overviews/ , except Reflection & Macros

We used transifex as our working platform, the address is https://www.transifex.com/projects/p/12345-1/

The translated doc list:

- The Scala Actors Migration Guide
- Value Classes and Universal Traits
- String Interpolation
- Implicit Classes
- Futures and Promises
- Scala’s Parallel Collections Library
- The Architecture of Scala Collections
- The Scala Actors API
- Scala’s Collections Library

### CODE REVIEW

**Comment by SethTisue** [comment]
@imsingo are you still interested in pursuing this?

**Comment by SethTisue** [comment]
@heathermiller @dickwall do we know of anyone who could review this?

**Comment by heathermiller** [comment]
Actually, no, I don't. For some reason I don't know any enthusiastic Chinese Scala programmers :(

**Comment by dickwall** [comment]
Sorry - me either. We could put a call out in the next scalawags maybe?

**Comment by SethTisue** [comment]
call for help put out on Twitter: https://twitter.com/scala_lang/status/635589047235252224

**Comment by eed3si9n** [comment]
When I need help reviewing Mandarin document for sbt I ping @pengisgood, @XuefengWu , @fsi206914, and @jasonqu and one of them magically show up. 先谢了!

**Comment by fsi206914** [comment]
I'd like to help out. and how to make a review?

**Comment by eed3si9n** [comment]
@fsi206914 Add comments on the commit if you find mistakes.
Also "更要特别感谢的是在此次翻译工作中付出辛勤劳动的、广大的翻译志愿者朋友们，他们是：
（以下按姓氏拼音排序）" in the overview page seem to indicate that this work was an effort of 21 volunteers. Is that correct? If so we could considered it more or less vetted.

**Comment by SethTisue** [comment]
when I try to build this branch locally, I get the same `wrong argument type Array (expected Regexp)` error that Heather saw in 2014. so at minimum, someone will need to make a new PR (since @imsingo has apparently disappeared) including the same commits plus a fix for that

**Comment by fsi206914** [comment]
@eed3si9n The google translation is correct.

**Comment by eed3si9n** [comment]
> when I try to build this branch locally, I get the same wrong argument type Array (expected Regexp) error that Heather saw in 2014. 

I don't think these guys actually ran Jekyll. The `wrong argument type Array` likely is coming from the incorrect `language/languages` YAML head matter (which I don't think is documented). I was able to fix that: eed3si9n/scala.github.com@ad733b8af0da07a34b791e71ef1c191e4edbf4fc

There are few more wiring up that are needed, but once they are done I can send a new PR.

**Comment by SethTisue** [comment]
closing since #450 was merged. if anyone's coming to this PR from Twitter, welcome, and see #450 for further to-dos

**Pull request closed without merging**
