### PR TITLE
removed cloneable and serializable

### PR DESCRIPTION
**Pull request by Philippus**
annotations as they are removed, also changed links to the current api instead of the 2.9.1 api

### CODE REVIEW

**Comment by Philippus** [comment]
can we restart this build?

**Comment by SethTisue** [comment]
@jvican I wanted to restart the build, but I'm unable to log in to the Scala Center's Drone instance. (I don't think I have attempted to login before; pretty sure this was my first time.) It takes me to GitHub to an authorization page, and I click "Authorize application", but it seems to get stuck in some sort of infinite back-and-forth reloading loop and never succeeds. is this something you can help with...?

**Comment by SethTisue** [comment]
@jvican ping

**Comment by SethTisue** [comment]
@jvican ping

**Comment by jvican** [comment]
Oh! I am very sorry about this, I completely missed this ping.
  
Can you try again? I think I fixed this one week ago and now it should work. You're in the Scala org, so you don't need more privileges than that :wink:. In any case, now I'll restart the build here.
  
Thanks for your patience!

**Comment by jvican** [comment]
@travissarles This may be of your interest, we were discussing it today :wink:.

**Comment by Philippus** [comment]
@SethTisue checks have passed. :)

**Comment by SethTisue** [comment]
thank you @Philippus!

**Pull request merged**
