### PR TITLE
Make Finding Implicits easier to read

### PR DESCRIPTION
**Pull request by janekdb**
- Drop first person voice
 - Dial down humour setting to 20% by removing distracting Other Dimensions
 - Add link to issues
 - Update links to language specification
 - Remove comment about revision of StackOverflow answer because the reader
   won't have seen the previous slightly incorrect version

### CODE REVIEW

**Comment by janekdb** [comment]
Need help on the build,

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by heathermiller** [comment]
Thanks for the ping, @janekdb. You just made me realize that I have the power to restart builds 🙂

Looks like the build just timed out. Trying again.

**Comment by SethTisue** [comment]
thanks Janek!

**Pull request merged**
