### PR TITLE
Fix an example that doesn't compile

### PR DESCRIPTION
**Pull request by lloydmeta**
The example on this page was wrong according to https://issues.scala-lang.org/browse/SI-9280

### CODE REVIEW

**Comment by gourlaysama** [comment]
Nice catch. I think it might be more useful here to use a float literal rather than changing the type to `Double`:
```scala
class HashMap[K,V](initialCapacity: Int = 16, loadFactor: Float = 0.75f)
```

**Comment by lloydmeta** [comment]
Done :+1:

**Comment by gourlaysama** [comment]
Ah, I just realized there are two more float literals that need to be added for the example to compile (line 60 and 64, `0.8f`).

**Comment by lloydmeta** [comment]
Nice catch fixed 60 and 64 as well.

**Comment by gourlaysama** [comment]
LGTM, thanks a lot! :sparkles:

/cc @heathermiller for merging :)

**Comment by heathermiller** [comment]
Sorry for the heinous delay on this! (not receiving notifications for some reason :/ )

**Comment by heathermiller** [comment]
LGTM!

**Pull request merged**
