### PR TITLE
Add new KO translations in Overviews.

### PR DESCRIPTION
**Pull request by Junbong**
Add new **KO** translations in Overviews. This series of KO translations will be continued.

### CODE REVIEW

**Comment by Junbong** [comment]
Can you please merge this PR priorly?

**Comment by heathermiller** [comment]
Many thanks for your contribution!! This is great, happy that a Korean translation of the collections overview is in progress!!
Are you planning on translating the entire guide? We like to wait until an entire document is translated and reviewed before merging. It can be a bit frustrating to users to find only one page translated but nothing else.

**Comment by Junbong** [comment]
@heathermiller OK. Maybe I need to translate more documents.

**Comment by SethTisue** [comment]
closing since there hasn't been any activity in a while. can be reopened anytime

**Pull request closed without merging**
