### PR TITLE
Document non-deprecated way of creating promises

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by SethTisue** [comment]
thanks for catching this! not ready for merge, yet, though, I think — the imports need updating as well

**Comment by raboof** [comment]
@SethTisue done for `Promise` - do we also want to change `future` to `Future`?

**Comment by SethTisue** [comment]
> do we also want to change future to Future

yes, I think that would be good.

**Comment by heathermiller** [comment]
Thanks @raboof! And thanks @SethTisue for the good suggestions – big +1 on updating to both `Future` and `Promise`

**Comment by SethTisue** [comment]
LGTM! thanks again

**Pull request merged**
